<html>
    <h1>ini adalah gambar menggunakan tag img </h1>
    <img src="img/gambar.png" alt="alternatif gambar ga ke reload " width="30%">
    <?php include "kembali.php"?>
</html>

<h2>KODE ASLI DI BAWAH INI:</h2>
<pre><code>
&lt;html&gt;
    &lt;h1&gt;ini adalah gambar menggunakan tag img &lt;/h1&gt;
    &lt;img src="img/gambar.png" alt="alternatif gambar ga ke reload " width="30%"&gt;
    &lt;?php include "kembali.php"?&gt;
&lt;/html&gt;
</code></pre>
