<html>
    <h1>Dibawah ini adalah paragraf</h1>
    <p>Isi paragraf: Contoh Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error at natus sapiente. Officiis exercitationem quibusdam esse animi. Iste amet quas temporibus ducimus eveniet sit, eligendi dolores, esse minus harum id.</p>
    <?php include "kembali.php"?>
</html>

<h2>Kode Asli Dibawah Ini:</h2>
<pre><code>
&lt;html&gt;
    &lt;h1&gt;Dibawah ini adalah paragraf&lt;/h1&gt;
    &lt;p&gt;Isi paragraf: Contoh Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error at natus sapiente. Officiis exercitationem quibusdam esse animi. Iste amet quas temporibus ducimus eveniet sit, eligendi dolores, esse minus harum id.&lt;/p&gt;
    &lt;?php include "kembali.php"?&gt;
&lt;/html&gt;
</code></pre>
