<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li><a href="HOME">HOME</a></li>
                <li><a href="ABOUT">TENTANG</a></li>
                <li><a href="CONTACT">KONTAK</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <article>
                <h3>JUDUL ARTIKEL 1</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Explicabo suscipit quibusdam aut commodi nesciunt quidem iste.
                    Beatae non officiis ipsum cum minima minus ratione fuga et earum? Molestias,
                    sed officiis?
                </p>
            </article>
            <article>
                <h3>JUDUL ARTIKEL 2</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Enim reprehenderit veritatis ab laboriosam necessitatibus officia quos.
                    Quaerat deserunt aspernatur architecto explicabo fuga distinctio, placeat laboriosam voluptatibus? Quibusdam nulla suscipit recusandae.
                </p>
            </article>
        </section>
    </main>

    <aside>
        <h2>NAVBAR SAMPING</h2>
        <p>Ini adalah konten dari sidebar yang bisa berisi iklan dan kebutuhan lainnya</p>
    </aside>

    <footer>
        <p>Hak Cipta &copy; Alief 2024</p>
    </footer>
    <?php include "kembali.php"?>
</body>
</html>

<h2>Kode Asli Dibawah Ini:</h2>
<pre><code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;

&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
    &lt;title&gt;Document&lt;/title&gt;
&lt;/head&gt;

&lt;body&gt;
    &lt;header&gt;
        &lt;nav&gt;
            &lt;ul&gt;
                &lt;li&gt;&lt;a href="HOME"&gt;HOME&lt;/a&gt;&lt;/li&gt;
                &lt;li&gt;&lt;a href="ABOUT"&gt;TENTANG&lt;/a&gt;&lt;/li&gt;
                &lt;li&gt;&lt;a href="CONTACT"&gt;KONTAK&lt;/a&gt;&lt;/li&gt;
            &lt;/ul&gt;
        &lt;/nav&gt;
    &lt;/header&gt;
    &lt;main&gt;
        &lt;section&gt;
            &lt;article&gt;
                &lt;h3&gt;JUDUL ARTIKEL 1&lt;/h3&gt;
                &lt;p&gt;Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Explicabo suscipit quibusdam aut commodi nesciunt quidem iste.
                    Beatae non officiis ipsum cum minima minus ratione fuga et earum? Molestias,
                    sed officiis?
                &lt;/p&gt;
            &lt;/article&gt;
            &lt;article&gt;
                &lt;h3&gt;JUDUL ARTIKEL 2&lt;/h3&gt;
                &lt;p&gt;Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Enim reprehenderit veritatis ab laboriosam necessitatibus officia quos.
                    Quaerat deserunt aspernatur architecto explicabo fuga distinctio, placeat laboriosam voluptatibus? Quibusdam nulla suscipit recusandae.
                &lt;/p&gt;
            &lt;/article&gt;
        &lt;/section&gt;
    &lt;/main&gt;

    &lt;aside&gt;
        &lt;h2&gt;NAVBAR SAMPING&lt;/h2&gt;
        &lt;p&gt;Ini adalah konten dari sidebar yang bisa berisi iklan dan kebutuhan lainnya&lt;/p&gt;
    &lt;/aside&gt;

    &lt;footer&gt;
        &lt;p&gt;Hak Cipta &amp;copy; Alief 2024&lt;/p&gt;
    &lt;/footer&gt;
    &lt;?php include "kembali.php"?&gt;
&lt;/body&gt;
&lt;/html&gt;
</code></pre>
